server:
  port: 8082
  context-path: /hotkeysdev


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456


solrUrl: http://192.168.1.111:8983/solr/hotkeys